// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp_mTsuYInDUMj4VS917E6ozorRWcnKic',
    appId: '1:189907732269:android:547d631fcaea1d56d475a4',
    messagingSenderId: '189907732269',
    projectId: 'my-point-84e64',
    storageBucket: 'my-point-84e64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMgxZGWe9KUoeD2lpAy865mNLFsUbGN5c',
    appId: '1:189907732269:ios:73acb2dc034003ecd475a4',
    messagingSenderId: '189907732269',
    projectId: 'my-point-84e64',
    storageBucket: 'my-point-84e64.firebasestorage.app',
    iosBundleId: 'kz.my-point.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0dIqUE_oauk2Z8yGIW4BtKRewGqmaSn4',
    appId: '1:189907732269:web:8005d34ad9aa4f2ed475a4',
    messagingSenderId: '189907732269',
    projectId: 'my-point-84e64',
    authDomain: 'my-point-84e64.firebaseapp.com',
    storageBucket: 'my-point-84e64.firebasestorage.app',
    measurementId: 'G-SVDV6BCC8N',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMgxZGWe9KUoeD2lpAy865mNLFsUbGN5c',
    appId: '1:189907732269:ios:15f00281945a5982d475a4',
    messagingSenderId: '189907732269',
    projectId: 'my-point-84e64',
    storageBucket: 'my-point-84e64.firebasestorage.app',
    iosBundleId: 'kz.my-point.myPoint',
  );
}
